
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int op_mul = 4;
  public static final int error = 1;
  public static final int igual = 5;
  public static final int ident = 2;
  public static final int op_mas = 3;
  public static final int EOF = 0;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "ident",
  "op_mas",
  "op_mul",
  "igual"
  };
}

