
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int constfloat = 19;
  public static final int tvoid = 3;
  public static final int coma = 6;
  public static final int tfloat = 5;
  public static final int op_sub = 14;
  public static final int pcoma = 7;
  public static final int tint = 4;
  public static final int op_div = 16;
  public static final int constlit = 20;
  public static final int par_C = 9;
  public static final int ident = 2;
  public static final int constint = 18;
  public static final int igual = 12;
  public static final int par_A = 8;
  public static final int EOF = 0;
  public static final int op_mul = 15;
  public static final int error = 1;
  public static final int op_mod = 17;
  public static final int llave_C = 11;
  public static final int return_ = 21;
  public static final int llave_A = 10;
  public static final int op_sum = 13;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "ident",
  "tvoid",
  "tint",
  "tfloat",
  "coma",
  "pcoma",
  "par_A",
  "par_C",
  "llave_A",
  "llave_C",
  "igual",
  "op_sum",
  "op_sub",
  "op_mul",
  "op_div",
  "op_mod",
  "constint",
  "constfloat",
  "constlit",
  "return_"
  };
}

