
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int xnor = 8;
  public static final int not = 13;
  public static final int nor = 6;
  public static final int numero = 14;
  public static final int menorIgual = 19;
  public static final int nand = 5;
  public static final int or = 4;
  public static final int menor = 17;
  public static final int pComa = 2;
  public static final int igual = 15;
  public static final int EOF = 0;
  public static final int pC = 10;
  public static final int error = 1;
  public static final int xor = 7;
  public static final int pA = 9;
  public static final int mayorIgual = 20;
  public static final int trueT = 11;
  public static final int falseF = 12;
  public static final int distinto = 16;
  public static final int and = 3;
  public static final int mayor = 18;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "pComa",
  "and",
  "or",
  "nand",
  "nor",
  "xor",
  "xnor",
  "pA",
  "pC",
  "trueT",
  "falseF",
  "not",
  "numero",
  "igual",
  "distinto",
  "menor",
  "mayor",
  "menorIgual",
  "mayorIgual"
  };
}

